% Program P2_7 - modified for Q2.29
clf;
h = [1 -2 3 4 -3 2 -1 1 3 6 -3 4 5 2 -1];	% impulse response
x = [2 4 5 3 -2 -1 3 -2 9 7];		% input sequence
y = conv(h,x);
n = 0:23;
subplot(2,1,1);
stem(n,y);
xlabel('Time index n'); ylabel('Amplitude');
title('Output Obtained by Convolution'); grid;
x1 = [x zeros(1,14)];
y1 = filter(h,1,x1);
subplot(2,1,2);
stem(n,y1);
xlabel('Time index n'); ylabel('Amplitude');
title('Output Generated by Filtering'); grid;
